FROM alpine:latest

#installing nginx
RUN apk add --update nginx && \ rm -rf /var/cache/apk/* && \  mkdir -p /run/nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

#Start
CMD ["nginx", "-g", "daemon off;"]
